services:
  app:
      build: .
      restart: always
      container_name: 'orders'
      command: sh -c "python manage.py runserver 0.0.0.0:8000"

      volumes:
        - static_volume:/app/static
      ports:
        - '8000:8000'

volumes:
    static_volume:
