# Generated by Django 5.1.5 on 2025-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_price_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
