# Generated by Django 5.1.5 on 2025-01-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
